export {appReducer} from './app-reducer'
export {authReducer} from './auth-reducer'
export {dialogsReducer} from './dialogs-reducer'
export {profileReducer} from './profile-reducer'
export {sidebarReducer} from './sidebar-reducer'
export {usersReducer} from './users-reducer'